apiVersion: v1
kind: Service
metadata:
  name: {{ template "stolon.fullname" . }}-postgres
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if (or (eq .Values.proxy.service.type "ClusterIP") (empty .Values.proxy.service.type)) }}
  type: ClusterIP
  {{- if .Values.proxy.service.clusterIP }}
  clusterIP: {{ .Values.proxy.service.clusterIP }}
  {{- end }}
  {{- else if eq .Values.proxy.service.type "LoadBalancer" }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- else }}
  type: {{ .Values.proxy.service.type }}
  {{- end }}
  ports:
  {{- range $key, $value := .Values.proxy.service.ports }}
    - name: {{ $key }}
      {{ toYaml $value | nindent 6 }}
  {{- end }}
  selector:
    app: {{ template "stolon.name" . }}
    release: {{ .Release.Name }}
    component: stolon-proxy
