apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "stolon.fullname" . }}-stolonctl
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "stolon.name" . }}
      release: {{ .Release.Name }}
      component: stolonctl
      name: {{ template "stolon.fullname" . }}-stolonctl
  template:
    metadata:
      labels:
        app: {{ template "stolon.name" . }}
        release: {{ .Release.Name }}
        component: stolonctl
        stolon-cluster: {{ template "stolon.fullname" . }}
        name: {{ template "stolon.fullname" . }}-stolonctl
        product: {{ template "stolon.name" . }}
    spec:
      serviceAccountName: {{ template "stolon.serviceAccountName" . }}
      securityContext:
        runAsUser: 0
      nodeSelector:
        gravitational.io/k8s-role: master
      containers:
        - name: stolonctl
          image: "{{ .Values.registry }}{{ .Values.stolonctlImage.repository }}:{{ .Values.stolonctlImage.tag }}"
          imagePullPolicy: {{ .Values.stolonctlImage.pullPolicy }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ETCD_ENDPOINTS
              value: "$(NODE_NAME):2379"
            {{- if not (empty .Values.store.caFile) }}
            - name: ETCD_CACERT
              value: {{ .Values.store.caFile | quote }}
            {{- end }}
            {{- if not (empty .Values.store.certFile) }}
            - name: ETCD_CERT
              value: {{ .Values.store.certFile | quote }}
            {{- end }}
            {{- if not (empty .Values.store.key) }}
            - name: ETCD_KEY
              value: {{ .Values.store.key | quote }}
            {{- end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret | quote }}
                  {{- else }}
                  name: {{ template "stolon.fullname" . }}
                  {{- end }}
                  key: "password"
          volumeMounts:
            - name: etcd-secrets
              mountPath: /home/stolon/secrets/etcd
      volumes:
        - name: etcd-secrets
          hostPath:
            path: /var/state
