{{- if .Values.existingSecret }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "stolon.fullname" . }}-update-secret
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: {{ template "stolon.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        gravitational.io/k8s-role: master
      restartPolicy: OnFailure
      serviceAccountName: {{ template "stolon.serviceAccountName" . }}
      containers:
        - name: update
          image: "{{ .Values.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/dumb-init", "--", "/usr/local/bin/update-secret.sh"]
          env:
            - name: PG_REPL_PASSWORD
              value: {{ "replpassword" | b64enc | quote }}
            - name: SECRET_NAME
              value: {{ .Values.existingSecret | quote }}
          volumeMounts:
            - name: kubectl
              mountPath: /usr/bin/kubectl
      volumes:
        - name: kubectl
          hostPath:
            path: /usr/bin/kubectl
{{- end }}
